language: python

python:
  - "3.6"

install:
  - pip3 install flake8
  - pip3 install flake8-docstrings
  - pip3 install Sphinx sphinx_rtd_theme

script:
  - flake8
  - sphinx-build -j auto docs docs-out
  - sphinx-build -j auto -b linkcheck docs docs-out
